# Generated by Django 3.2.4 on 2021-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tag',
            field=models.ManyToManyField(blank=True, to='hw1.HashTag'),
        ),
    ]
